### PR TITLE
Develop-change catalog layout, ignore idea

### PR DESCRIPTION
**Pull request by emilylxf**

### CODE REVIEW

**Comment by yifeili98** [comment]
Please exclude files in /.idea folder

**Comment by yifeili98** [comment]
If .idea is added by git add *, please be careful with using * in the future...

**Comment by yifeili98** [comment]
Please do not merge before PR is approved...

**Comment by emilylxf** [comment]
> Please do not merge before PR is approved...
ok. Thank you vey much. I clicked that button by accident. I am sorry.

**Comment by emilylxf** [comment]
> Please do not merge before PR is approved...

Ok. Thank you very much.

**Comment by emilylxf** [comment]
> If .idea is added by git add *, please be careful with using * in the future...

OK. I will pay attention to that in future. Thanks.

**Comment by emilylxf** [comment]
> Please exclude files in /.idea folder

OK. I have done that now.

**Pull request merged**
